# -*- coding: utf-8 -*-
"""Quiz_generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YIWKjhl84rFtX0_qr5K1E48CAmIO88T4
"""

import ipywidgets as widgets
from IPython.display import display, clear_output

# Quiz questions (expanded for bioengineering)
quiz = [
    {
        'question': 'Which biomolecule is most abundant in cell membranes?',
        'options': ['Proteins', 'Lipids', 'Carbohydrates', 'Nucleic acids'],
        'answer': 1
    },
    {
        'question': 'CRISPR-Cas9 is primarily used for:',
        'options': ['Protein folding', 'DNA sequencing', 'Gene editing', 'Cell imaging'],
        'answer': 2
    },
    {
        'question': 'A biosensor usually consists of:',
        'options': ['Antibody and metal', 'Bioreceptor and transducer', 'Enzyme and polymer', 'Sensor and amplifier'],
        'answer': 1
    }
]

# Simple user login setup (just username)
user_db = set()

def start_login():
    login_output = widgets.Output()
    reg_output = widgets.Output()

    username_input = widgets.Text(description="Username:")
    login_button = widgets.Button(description="Login", button_style='info')
    register_button = widgets.Button(description="Register", button_style='success')

    def on_login(b):
        with login_output:
            clear_output()
            uname = username_input.value.strip()
            if uname in user_db:
                print(f"Welcome back, {uname}!")
                clear_output(wait=True)
                start_quiz(uname)
            else:
                print("Username not found. Please register or try again.")

    def on_register(b):
        with reg_output:
            clear_output()
            uname = username_input.value.strip()
            if not uname:
                print("Enter a non-empty username.")
                return
            if uname in user_db:
                print("Username already registered. Please login.")
            else:
                user_db.add(uname)
                print("Registration successful! You can now login.")

    login_button.on_click(on_login)
    register_button.on_click(on_register)

    display(widgets.VBox([
        widgets.HTML("<h3>Bioengineering Quiz Login</h3>"),
        username_input,
        widgets.HBox([login_button, register_button]),
        login_output,
        reg_output
    ]))

def start_quiz(username):
    user_answers = []
    question_widgets = []

    def make_question_widget(qdata, idx):
        radio = widgets.RadioButtons(
            options=qdata['options'],
            description=f"Q{idx+1}:",
            disabled=False
        )
        return radio

    question_widgets = [
        make_question_widget(q, i) for i, q in enumerate(quiz)
    ]

    submit_button = widgets.Button(description='Submit Quiz', button_style='primary')
    output = widgets.Output()

    def on_submit(b):
        score = 0
        for i, radio in enumerate(question_widgets):
            selected = radio.index
            correct = quiz[i]['answer']
            if selected == correct:
                score += 1
        with output:
            clear_output()
            print(f"{username}, your score is: {score} / {len(quiz)}\n")
            for i, radio in enumerate(question_widgets):
                answer = quiz[i]['options'][quiz[i]['answer']]
                result = "✅" if radio.index == quiz[i]['answer'] else "❌"
                print(f"Q{i+1}: {result} (Correct: {answer})")

    submit_button.on_click(on_submit)

    display(widgets.VBox(
        [widgets.HTML(f"<h4>Bioengineering Quiz for {username}</h4>")]
        + question_widgets
        + [submit_button, output]
    ))

# Start the login
start_login()